org: feliperodalves
app: trigger-dynamo
service: trigger-dynamo

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  hero-insert:
    handler: handler.heroesInsert
    events:
      - http:
          path: heroes
          method: post
          cors: true
